export default [
    "Bananas are technically berries, but strawberries aren’t!",
    "The inside of a banana peel can polish shoes or soothe a mosquito bite.",
    "Bananas float in water, just like apples and watermelons!",
    "Strawberries are the only fruit with seeds on the outside — about 200 per berry!",
    "Ancient Romans used strawberries to treat everything from depression to fever.",
    "In France, strawberries are considered an aphrodisiac.",
    "It takes nearly 2 years for a pineapple to grow and ripen!",
    "Pineapple contains bromelain, an enzyme that can tenderize meat — and even tingle your tongue.",
    "In the 1700s, pineapples were rented as table centerpieces to impress guests.",
    "Watermelon is 92% water — perfect for hot days.",
    "Every part of a watermelon is edible, even the rind and seeds.",
    "Square watermelons are real! They’re grown in boxes in Japan for easier stacking.",
    "Mangoes are the most consumed fruit in the world.",
    "In India, mango is called the “King of Fruits.”",
    "Unripe mango can be turned into spicy pickles, not just smoothies!",
    "Lemons were so valuable in the 1700s, British sailors carried them to prevent scurvy.",
    "Lemon trees can produce fruit all year round.",
    "Lemon juice can glow faintly under UV light — spooky and citrusy!",
    "Oranges were originally green, not orange!",
    "A single orange can give you 100% of your daily vitamin C.",
    "In the Middle Ages, orange peels were used as air fresheners.",
    "Blueberries can improve memory and brain function.",
    "They are one of the only naturally blue foods in the world.",
    "Early American colonists made blue paint from blueberry skins.",
    "Coconut water is sterile and has been used in emergency IVs.",
    "A coconut is not a nut — it’s a drupe!",
    "In Sanskrit, the coconut is called \"Kalpavriksha,\" meaning “the tree that gives everything.”",
    "The word “cocktail” was first used in 1806 and referred to a mix of spirits, bitters, sugar, and water.",
    "Frozen blended drinks became popular after the invention of the electric blender in the 1920s.",
    "Mocktails (non-alcoholic cocktails) have become a global trend for wellness-focused fun!"
]